apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJWakNCL3FBREFnRUNBZ0VBTUFvR0NDcUdTTTQ5QkFNQ01DTXhJVEFmQmdOVkJBTU1HR3N6Y3kxelpYSjIKWlhJdFkyRkFNVFU0TVRReE1qVXlNREFlRncweU1EQXlNVEV3T1RFMU1qQmFGdzB6TURBeU1EZ3dPVEUxTWpCYQpNQ014SVRBZkJnTlZCQU1NR0dzemN5MXpaWEoyWlhJdFkyRkFNVFU0TVRReE1qVXlNREJaTUJNR0J5cUdTTTQ5CkFnRUdDQ3FHU000OUF3RUhBMElBQk9wVWMzYktTQVBacm1SNitZcmxxUjRJZ2h4UDdaZ0NUTHRBd3Vvc0haL2IKR2JxL3hBcjlvRkdDUHBleTJvdUVhVFhtTUpOTlRWaUIwdGQzRXhkNjBvMmpJekFoTUE0R0ExVWREd0VCL3dRRQpBd0lDcERBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUFvR0NDcUdTTTQ5QkFNQ0EwY0FNRVFDSUNpUzNGVmF6RnRBCjlKTVE5amh1UG1qMUk5dHMzUWZTNWdOY3lDV1dDeFFKQWlBa0lnWFZvUEswemJqenJVNS9uaGdFV1RiZ0JIL0EKdHNFS0p3dFBSSnpoQ1E9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://192.168.64.24:6443
  name: default
contexts:
- context:
    cluster: default
    user: default
  name: default
current-context: default
kind: Config
preferences: {}
users:
- name: default
  user:
    password: b0f7735010082aa0582bce7cfd41c2c1
    username: admin
