apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJWakNCL3FBREFnRUNBZ0VBTUFvR0NDcUdTTTQ5QkFNQ01DTXhJVEFmQmdOVkJBTU1HR3N6Y3kxelpYSjIKWlhJdFkyRkFNVFU0TVRReE5qZ3pNakFlRncweU1EQXlNVEV4TURJM01USmFGdzB6TURBeU1EZ3hNREkzTVRKYQpNQ014SVRBZkJnTlZCQU1NR0dzemN5MXpaWEoyWlhJdFkyRkFNVFU0TVRReE5qZ3pNakJaTUJNR0J5cUdTTTQ5CkFnRUdDQ3FHU000OUF3RUhBMElBQkI4aFhHVjRBcS81UW1VQ2dYMXJ1aDQxbDZ5QWtFSlFNbkhKQTI0c2g2YmgKcUJ4WkdYTDY1dnpERGdWbXQvYVFoYzVyMTg2MmdVTVdOTXFsaWhPU3RpQ2pJekFoTUE0R0ExVWREd0VCL3dRRQpBd0lDcERBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUFvR0NDcUdTTTQ5QkFNQ0EwY0FNRVFDSUJIMmJKN0dGUkJDCmU2bDl3WEcxanJOZlN1bXZPa1NOUXZqZ1RwYWhlTmJ2QWlCV0pmWWRydFhuMENIb3dBbE4xTGI2NDNwM1NqMkUKczBaR3QvTGQzZnZGalE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://192.168.64.23:6443
  name: default
contexts:
- context:
    cluster: default
    user: default
  name: default
current-context: default
kind: Config
preferences: {}
users:
- name: default
  user:
    password: f92e31773f9daa00f87474989b2d309d
    username: admin
