apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJXRENCL3FBREFnRUNBZ0VBTUFvR0NDcUdTTTQ5QkFNQ01DTXhJVEFmQmdOVkJBTU1HR3N6Y3kxelpYSjIKWlhJdFkyRkFNVFU0TVRReE5ESXpNREFlRncweU1EQXlNVEV3T1RRek5UQmFGdzB6TURBeU1EZ3dPVFF6TlRCYQpNQ014SVRBZkJnTlZCQU1NR0dzemN5MXpaWEoyWlhJdFkyRkFNVFU0TVRReE5ESXpNREJaTUJNR0J5cUdTTTQ5CkFnRUdDQ3FHU000OUF3RUhBMElBQkRjZ1ZzeVlOMXpKZnBTNUxDVUNhcnJ1ZnorQi81eXJIRmdTM1ljWWxZckoKSjA1Yk83WHpCeTlWMHZQSjdaVTRpbzY3cTFDcFF5aE1IRW91ajgzeUx3bWpJekFoTUE0R0ExVWREd0VCL3dRRQpBd0lDcERBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUFvR0NDcUdTTTQ5QkFNQ0Ewa0FNRVlDSVFDN2dJOGRoMXo5CktnY1VDM2l1VGF2bXdRNzZNcTBseGtoYnNIVkxTWGdIendJaEFLcVlXTks0QnJ0VEZzVUxPWjlYSENmMmdGUDYKL1dralo4V0YyT0NWb084QgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://192.168.64.25:6443
  name: default
contexts:
- context:
    cluster: default
    user: default
  name: default
current-context: default
kind: Config
preferences: {}
users:
- name: default
  user:
    password: 771098dfba1d72a7fa53ab4ff9d8f12d
    username: admin
